# Generated by Django 5.0 on 2023-12-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='photo',
        ),
        migrations.AddField(
            model_name='skill',
            name='font_awesome',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
