# Generated by Django 5.0 on 2023-12-30 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_remove_skill_photo_skill_font_awesome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='task',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='folio.skill'),
        ),
        migrations.AddField(
            model_name='task',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='folio.experience'),
        ),
    ]
